#!/bin/bash
#
FC='mpif90'
CC='mpicc'
LINK='mpif90'
CPP='cpp -P -traditional'
MPI='true'
DEFINES='-DWORDLENGTH=4'
# INCLUDES='-I/opt/apps/intel13/mvapich2/1.9/include -I/opt/apps/intel13/netcdf/4.2.1.1/include'
# INCLUDES='-I/opt/apps/intel13/mvapich2/1.9/include -I/opt/apps/intel13/netcdf/3.6.3/k1om/include'
 INCLUDES="-I/opt/apps/intel13/mvapich2/1.9/include -I${TACC_NETCDF_INC}"
# INCLUDES="-I/opt/apps/intel13/mvapich2/1.9/include -I${MIC_TACC_NETCDF_INC}"

# lIBS='-L/opt/apps/intel13/netcdf/4.2.1.1/lib -lnetcdf'
# lIBS='-L/opt/apps/intel13/netcdf/3.6.3/k1om/lib -lnetcdf'
# lIBS="-L${TACC_NETCDF_LIB} -lnetcdf"
 LIBS="-L${TACC_NETCDF_LIB} -lnetcdf"
# LIBS="-L${TACC_NETCDF_LIB} -lnetcdf"


NOOPTFILES='exf_swapffields.F ecco_cost_final.F'
NOOPTFLAGS='-O0'
#
#   FOPTIM='-fast -tp barcelona-64'
#    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'

#  FFLAGS="$FFLAGS -convert big_endian -assume byterecl "
#  FFLAGS="$FFLAGS -w95 -W0 -WB -xT -fno-alias -assume byterecl -convert big_endian"
  FFLAGS="$FFLAGS  -W0 -WB -fno-alias -assume byterecl -convert big_endian"

#  FFLAGS= '-convert big_endian -assume byterecl'

#    FOPTIM='-fast -tp barcelona-64'
#      FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
#      FOPTIM='-tp barcelona-64 -O0 -Munroll -Kieee'
#  fi
